column_width = 120
line_endings = "Unix"
indent_type = "Spaces"
indent_width = 2
quote_style = "AutoPreferDouble"
# Always apply parentheses on function calls with a single string/table argument.
call_parentheses = "Always"
